### PR TITLE
#544 Remove html entities before xml parsing messages

### LINKED ISSUE #544: Remove html entities before xml parsing messages
### Steps to Reproduce:
Call `PresentationMLParser.getTextContent(presentationML);` with the following presentationML
```
<div data-format="PresentationML" data-version="2.0">&nbsp;</div>
```
### Expected Result:
Java BDK should be able to extract content from a presentationML containing `&nbsp;` symbol.

### Actual Result:
```
[Fatal Error] :1:60: The entity "nbsp" was referenced, but not declared.
Failed to parse the PresentationML
```

### PR DESCRIPTION
**Pull request by symphony-mariacristina**
### Ticket
closes #544 

### Description
Goal of this PR is to enable the BDK to extract content from a presentationML which contains HTML specific tags.

### Checklist
- [x] Referenced a ticket in the PR title and in the corresponding section
- [x] Filled properly the description and dependencies, if any
- [x] Unit tests updated or added
- [x] Javadoc added or updated
- [x] Updated the documentation in [docs folder](../docs)

### CODE REVIEW

File: symphony-bdk-core/src/test/java/com/symphony/bdk/core/util/PresentationMLParserTest.java [hunk 1]
```diff
@@ -34,6 +34,14 @@ void getMessageFromPresentationMLNotTrimTest() throws PresentationMLParserExcept
     assertEquals(content.trim(), "This is a link to Symphony's Website");
   }
 
+  @Test
+  void getMessageFromPresentationMLWithEscapedContentTest() throws PresentationMLParserException {
+    String presentationML = "<div data-format=\"PresentationML\" data-version=\"2.0\">&nbsp;</div>";
+    String content = PresentationMLParser.getTextContent(presentationML, false);
+
+    assertNotEquals(content, "&#160;");
```
Comment (symphony-youri) [inline symphony-bdk-core/src/test/java/com/symphony/bdk/core/util/PresentationMLParserTest.java:42]: and what should it be equals to? :) " " (that would be more restrictive)

Comment (symphony-mariacristina) [reply symphony-bdk-core/src/test/java/com/symphony/bdk/core/util/PresentationMLParserTest.java:42]: my mistake! Let me fix it!

**Review by symphony-thibault — APPROVED** [review]

**Review by symphony-elias — APPROVED** [review]

**Review by symphony-youri — APPROVED** [review]
